# Generated by Django 6.0.7 on 2026-08-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waitlist', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitlist',
            options={},
        ),
        migrations.RenameField(
            model_name='waitlist',
            old_name='joined_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='waitlist',
            name='source',
            field=models.CharField(default='landing-page', max_length=50),
        ),
    ]
